# Results will be saved to neosr/experiments/results/

name = "test_super_compact_34_10_x1_pretrain"
model_type = "image"
scale = 1
#use_amp = true
#compile = true

[datasets.test_1]
name = "val_1"
type = "paired"
dataroot_lq = 'C:\Users\Fernando\Documents\Unicamp\IA_376_GAN\workspace\dgm-2025.2\projects\super-video-decompression\data\processed\lq_34_10_splitdb\test\lq'
dataroot_gt = 'C:\Users\Fernando\Documents\Unicamp\IA_376_GAN\workspace\dgm-2025.2\projects\super-video-decompression\data\processed\lq_34_10_splitdb\test\hq'


[val]
save_img = false
tile = 200
suffix = ""
[val.metrics.psnr]
type = "calculate_psnr"
[val.metrics.ssim]
type = "calculate_ssim"
[val.metrics.dists]
type = "calculate_dists"
better = "lower"
#[val.metrics.topiq]
#type = "calculate_topiq"

[network_g]
type = "compact"
num_conv = 8  # ultra compact
num_feat = 24 # super ultra compact

[path]
pretrain_network_g = 'C:\Users\Fernando\Documents\Unicamp\IA_376_GAN\workspace\dgm-2025.2\projects\super-video-decompression\data\1x-SuperUltraCompact-Pretrain.pth'
